### ISSUE TITLE
Add a way to store and read word tuples

### ISSUE THREAD

**Issue by Power-PP** [SigSegvSquad/WordLink#4]
- [x] Create a new directory
- [x] Structure to store data (comma, space, tab)
- [x] Code cell in notebook to read data

**Comment by OverPoweredDev** [comment]
Marked complete with 3e58694ba9560a4980cdbb85ce1a7da050ad4c0b. Comma separated structure is preferred because of whitespaces in names. added relations.py instead of code cell in notebook
